"""
Case Report Generator
======================
Produces a court-ready PDF case file for a single entity (suspect, location,
or vehicle), pulling together everything the analysis pipeline knows about
it: network position, connections, call records, transactions, and the FIR
excerpts that mention it.

The report also embeds a SHA-256 hash of its own content plus the current
tip of the tamper-proof evidence chain. Anyone reviewing the report later
can recompute that hash and compare it against the chain to confirm the
report was not altered after it was generated — the same chain-of-custody
guarantee the dashboard's audit trail provides, extended to the physical
document itself.
"""

import hashlib
import io
import time
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="CaseTitle", fontSize=20, leading=24, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#0B0F14"), spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name="CaseSubtitle", fontSize=9, leading=12, fontName="Courier",
        textColor=colors.HexColor("#59636E"), spaceAfter=14,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeading", fontSize=12, leading=16, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1E2833"), spaceBefore=16, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="Body", fontSize=9.5, leading=14, fontName="Helvetica",
        textColor=colors.HexColor("#20272E"),
    ))
    styles.add(ParagraphStyle(
        name="Mono", fontSize=8, leading=12, fontName="Courier",
        textColor=colors.HexColor("#59636E"),
    ))
    return styles


def generate_case_report(entity: dict, generated_by: str, audit_chain: list) -> bytes:
    """Build a PDF case report for one entity. Returns the raw PDF bytes."""
    styles = _styles()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=22 * mm, bottomMargin=18 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )
    story = []

    # ---- Header ----
    story.append(Paragraph("CASE FILE — ENTITY INVESTIGATION REPORT", styles["CaseTitle"]))
    story.append(Paragraph(
        "PS-26189 &nbsp;·&nbsp; MINISTRY OF HOME AFFAIRS — NCRB, WOMEN SAFETY DIVISION<br/>"
        "AI-Powered Criminal Network Analysis System",
        styles["CaseSubtitle"]
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1E2833"), spaceAfter=14))

    meta_table = Table([
        ["Generated", datetime.now().strftime("%d %B %Y, %H:%M:%S")],
        ["Generated By", generated_by],
        ["Entity Type", entity.get("type", "Unknown")],
        ["Entity Name", entity.get("name", "")],
    ], colWidths=[110, 380])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#59636E")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_table)

    # ---- Network Position ----
    if entity.get("rank"):
        r = entity["rank"]
        story.append(Paragraph("NETWORK POSITION", styles["SectionHeading"]))
        story.append(Paragraph(
            f"This individual ranks <b>#{r['rank']}</b> by influence within the analyzed network "
            f"(PageRank {r['pagerank']:.3f}, betweenness centrality {r['betweenness_centrality']:.3f}, "
            f"degree centrality {r['degree_centrality']:.3f}). Higher rank indicates a more central "
            f"role connecting other individuals in the network.",
            styles["Body"]
        ))

    # ---- Connections ----
    if entity.get("connections"):
        story.append(Paragraph(f"DIRECT CONNECTIONS ({len(entity['connections'])})", styles["SectionHeading"]))
        rows = [["Connected Entity", "Relationship", "Direction"]]
        for c in entity["connections"]:
            rows.append([c["name"], c["relation"].replace("_", " "), c["direction"]])
        t = Table(rows, colWidths=[170, 170, 120])
        t.setStyle(_table_style())
        story.append(t)

    # ---- Call Records ----
    if entity.get("call_records"):
        story.append(Paragraph(f"CALL DETAIL RECORDS ({len(entity['call_records'])})", styles["SectionHeading"]))
        rows = [["With", "Timestamp", "Duration", "Tower Location", "Direction"]]
        for c in entity["call_records"]:
            rows.append([c["with"], c["timestamp"], f"{c['duration_sec']}s", c["location"], c["direction"]])
        t = Table(rows, colWidths=[90, 105, 55, 90, 65])
        t.setStyle(_table_style())
        story.append(t)

    # ---- Financial Transactions ----
    if entity.get("transactions"):
        story.append(Paragraph(f"FINANCIAL TRANSACTIONS ({len(entity['transactions'])})", styles["SectionHeading"]))
        rows = [["With", "Amount (Rs.)", "Mode", "Timestamp", "Direction"]]
        for t_ in entity["transactions"]:
            rows.append([t_["with"], f"{int(t_['amount']):,}", t_["mode"], t_["timestamp"], t_["direction"]])
        t = Table(rows, colWidths=[90, 90, 55, 105, 65])
        t.setStyle(_table_style())
        story.append(t)

    # ---- FIR Mentions ----
    if entity.get("fir_mentions"):
        story.append(Paragraph(f"FIR / SOURCE DOCUMENT MENTIONS ({len(entity['fir_mentions'])})", styles["SectionHeading"]))
        for snippet in entity["fir_mentions"]:
            story.append(Paragraph(f"&bull; {snippet}", styles["Body"]))
            story.append(Spacer(1, 4))

    # ---- Chain-of-custody / verification block ----
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1E2833"), spaceAfter=8))
    story.append(Paragraph("EVIDENCE INTEGRITY VERIFICATION", styles["SectionHeading"]))

    latest_block_hash = audit_chain[-1]["block_hash"] if audit_chain else "N/A — no audit chain entries yet"
    report_fingerprint_input = f"{entity.get('name')}|{generated_by}|{latest_block_hash}|{int(time.time())}"
    report_hash = hashlib.sha256(report_fingerprint_input.encode()).hexdigest()

    story.append(Paragraph(
        "This report was generated from data verified against the system's tamper-proof evidence "
        "audit chain. The chain's most recent block hash at the time of generation is recorded below. "
        "To verify this report has not been altered since issuance, confirm this hash matches the "
        "corresponding entry in the live audit chain.",
        styles["Body"]
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Audit chain tip (at generation): <font face='Courier'>{latest_block_hash}</font>", styles["Mono"]))
    story.append(Paragraph(f"Report fingerprint (SHA-256): <font face='Courier'>{report_hash}</font>", styles["Mono"]))
    story.append(Spacer(1, 14))
    story.append(Paragraph(
        "This document is system-generated and intended to support, not replace, investigator "
        "judgment and due legal process. Findings are derived from automated NLP/graph analysis of "
        "the source records listed above.",
        ParagraphStyle(name="Disclaimer", fontSize=7.5, leading=11, fontName="Helvetica-Oblique",
                        textColor=colors.HexColor("#8B98A5"))
    ))

    doc.build(story)
    return buffer.getvalue()


def _table_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E2833")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F6F8")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D7DD")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ])
